version: '3.8'
services:
  # Serviço para o PostgreSQL
  postgres:
    image: postgres:latest
    environment:
      POSTGRES_DB: food
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    networks:
      - local

  # Serviço para a aplicação Spring Boot
  cardapio:
    build: .
    environment:
      DB_HOST: postgres
      DB_USER: postgres
      DB_PASS: root
    ports:
      - "8080:8080"
    depends_on:
      - postgres
    networks:
      - local

networks:
  local:
    driver: bridge